runtime: nodejs18
env: standard

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5  # 降低最大实例数
  target_throughput_utilization: 0.6

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "/cloudsql/eon-web-445802:asia-southeast1:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eon-user-2024"
  DB_NAME: "eon_protocol"
  JWT_SECRET: "your-secret-key"
  CLOUD_SQL_CONNECTION_NAME: "eon-web-445802:asia-southeast1:eon-db"

vpc_access_connector:
  name: "projects/eon-social-media-auto/locations/asia-southeast1/connectors/vpc-connector"
