runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "eon-jwt-secret-2024"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  PORT: "8080"
  NODE_OPTIONS: "--max-old-space-size=512 --trace-warnings"
  NPM_CONFIG_LOGLEVEL: "error"
  NPM_CONFIG_PRODUCTION: "true"
  NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always
    http_headers:
      X-Frame-Options: DENY
      X-XSS-Protection: '1; mode=block'
      X-Content-Type-Options: nosniff
      Strict-Transport-Security: 'max-age=31536000; includeSubDomains'
      Content-Security-Policy: "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"
      Referrer-Policy: strict-origin-when-cross-origin

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

entrypoint: node server.js

beta_settings:
  cloud_sql_instances: eonhome-445809:asia-southeast2:eon-db

vpc_access_connector:
  name: projects/eonhome-445809/locations/asia-southeast2/connectors/eon-connector

# 安全设置
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "18"
