runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "eon-jwt-secret-2024"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  PORT: "8080"
  DEPLOY_TIME: "$(date +%Y%m%dt%H%M%S)"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: |
    echo "=== Step 1: Environment Setup ==="
    echo "Current directory: $(pwd)"
    echo "Node version: $(node -v)"
    echo "NPM version: $(npm -v)"
    
    echo "=== Step 2: Workspace Preparation ==="
    echo "Workspace directory before cleanup:"
    ls -la /workspace || true
    echo "Cleaning workspace directory..."
    rm -rf /workspace/* || true
    mkdir -p /workspace
    
    echo "=== Step 3: File Copy ==="
    echo "Copying files to workspace..."
    cp -r . /workspace/
    cd /workspace
    echo "Verifying critical files..."
    for file in server.js routes/proxy.js package.json; do
      if [ ! -f "$file" ]; then
        echo "Error: $file not found!"
        exit 1
      fi
      echo "Found $file:"
      cat "$file"
      echo "=== End of $file ==="
    done
    
    echo "=== Step 4: Dependencies ==="
    echo "Installing dependencies..."
    npm install --production
    
    echo "=== Step 5: Final Verification ==="
    echo "Checking server.js line 294 and surrounding context:"
    echo "Lines 290-300 of server.js:"
    sed -n '290,300p' server.js || true
    echo "Workspace directory structure:"
    ls -R
    echo "Server.js line count:"
    wc -l server.js
    echo "Proxy.js line count:"
    wc -l routes/proxy.js
    
    echo "=== Step 6: File Permissions ==="
    echo "Setting correct permissions..."
    chmod -R 755 .
    
    echo "=== Step 7: Starting Application ==="
    echo "Starting in directory: $(pwd)"
    NODE_OPTIONS="--trace-warnings" npm start
