runtime: nodejs18
env: standard

basic_scaling:
  max_instances: 1
  idle_timeout: 10m

vpc_access_connector:
  name: projects/eon-web-445802/locations/asia-southeast2/connectors/vpc-connector

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "/cloudsql/eon-web-445802:asia-southeast2:eon-db-jakarta"
  DB_NAME: "eon_protocol"
  DB_USER: "eonuser"
  DB_PASSWORD: "eon-user-2024"
  JWT_SECRET: "your-secret-key"

beta_settings:
  cloud_sql_instances: eon-web-445802:asia-southeast2:eon-db-jakarta
