runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "eon-jwt-secret-2024"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  PORT: "8080"
  NODE_OPTIONS: "--max-old-space-size=512 --trace-warnings"
  NPM_CONFIG_LOGLEVEL: "error"
  NPM_CONFIG_PRODUCTION: "true"
  NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

entrypoint: |
  rm -rf node_modules package-lock.json &&
  mkdir -p node_modules &&
  chmod -R 777 node_modules &&
  npm install --production --no-optional --no-audit --no-package-lock &&
  node server.js
