runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  ADMIN_PASSWORD: "eonprotocol"
  JWT_SECRET: "eonprotocol"
  API_KEY: "eonprotocol"

beta_settings:
  cloud_sql_instances: "eonhome-445809:asia-southeast2:eon-db"

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: node server.js

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/_ah/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

inbound_services:
- warmup
