runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "${JWT_SECRET}"
  DB_HOST: "/cloudsql/${PROJECT_ID}:${REGION}:eon-db"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  PORT: "8080"
  DEPLOY_VERSION: "20250115t130000"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: |
    echo "Current directory: $(pwd)"
    echo "Listing workspace directory:"
    ls -la /workspace || true
    echo "Current server.js content:"
    cat /workspace/server.js || true
    echo "=== End of current server.js ==="
    echo "Cleaning up old files..."
    rm -rf /workspace/* || true
    echo "Copying new files..."
    cp -r . /workspace/
    echo "New server.js content:"
    cat /workspace/server.js
    echo "=== End of new server.js ==="
    echo "Starting application..."
    cd /workspace
    npm start
