runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "eon-jwt-secret-2024"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  PORT: "8080"
  DEPLOY_TIME: "$(date +%Y%m%dt%H%M%S)"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: |
    echo "Current directory: $(pwd)"
    echo "Workspace directory before cleanup:"
    ls -la /workspace || true
    echo "Cleaning workspace directory..."
    rm -rf /workspace/* || true
    echo "Copying files to workspace..."
    cp -r . /workspace/
    echo "Installing dependencies..."
    cd /workspace
    npm install
    echo "Workspace directory after setup:"
    ls -la /workspace
    echo "Server.js content:"
    cat /workspace/server.js
    echo "Starting application..."
    npm start
