runtime: nodejs18
env: standard

instance_class: B1

manual_scaling:
  instances: 1

vpc_access_connector:
  name: projects/eon-web-445802/locations/asia-southeast2/connectors/vpc-connector

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eon-user-2024"
  DB_NAME: "eon_protocol"
  JWT_SECRET: "your-secret-key"
  CLOUD_SQL_CONNECTION_NAME: "eonhome-445809:asia-southeast2:eon-db"

beta_settings:
  cloud_sql_instances: eonhome-445809:asia-southeast2:eon-db
