runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  PORT: "8081"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  ADMIN_PASSWORD: "eonprotocol"
  JWT_SECRET: "eonprotocol"
  API_KEY: "eonprotocol"

beta_settings:
  cloud_sql_instances: "eonhome-445809:asia-southeast2:eon-db"

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: node server.js

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
