runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "${JWT_SECRET}"
  DB_HOST: "/cloudsql/${PROJECT_ID}:${REGION}:eon-db"
  DB_USER: "${DB_USER}"
  DB_PASSWORD: "${DB_PASSWORD}"
  DB_NAME: "${DB_NAME}"
  PORT: "8080"
  DEPLOY_VERSION: "20250115t130000"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

entrypoint: |
    echo "Current server.js content:"
    cat /workspace/server.js
    echo "=== End of server.js ==="
    rm -rf /workspace/server.js.bak || true
    mv /workspace/server.js /workspace/server.js.bak || true
    cp server.js /workspace/server.js
    npm start
