runtime: nodejs18
env: standard

instance_class: B1

manual_scaling:
  instances: 1

handlers:
  - url: /.*
    script: auto
    http_headers:
      Access-Control-Allow-Origin: '*'
      Access-Control-Allow-Methods: 'GET, POST, PUT, DELETE, OPTIONS'
      Access-Control-Allow-Headers: 'Origin, X-Requested-With, Content-Type, Accept, Authorization'

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  JWT_SECRET: "your-secret-key"
  CLOUD_SQL_CONNECTION_NAME: "eonhome-445809:asia-southeast2:eon-db"

beta_settings:
  cloud_sql_instances: "eonhome-445809:asia-southeast2:eon-db"
