runtime: nodejs18
env: standard
instance_class: F1

env_variables:
  NODE_ENV: "production"
  API_KEY: "eon-api-key-2024"
  JWT_SECRET: "eon-jwt-secret-2024"
  DB_HOST: "/cloudsql/eonhome-445809:asia-southeast2:eon-db"
  DB_USER: "eonuser"
  DB_PASSWORD: "eonprotocol"
  DB_NAME: "eon_protocol"
  PORT: "8080"
  NODE_OPTIONS: "--max-old-space-size=512 --trace-warnings"
  NPM_CONFIG_LOGLEVEL: "error"
  NPM_CONFIG_PRODUCTION: "true"
  NPM_CONFIG_REGISTRY: "https://registry.npmjs.org/"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /.*
    script: auto
    secure: always

readiness_check:
  path: "/_ah/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

entrypoint: node server.js

# 添加临时目录配置
volumes:
  - name: ramdisk
    volume_type: tmpfs
    size_gb: 0.5

# 添加文件系统配置
beta_settings:
  cloud_sql_instances: eonhome-445809:asia-southeast2:eon-db
